### ISSUE TITLE
Apikit does not validate URI parameters marked as "number"

### ISSUE THREAD

**Issue by dmartinezg** [mulesoft/osprey-cli#35]
I have this RAML:

``` yaml
    /pages: &pages
      type: collection
      /{pageId}:
        uriParameters:
          pageId:
            type: number
            description: The page's numeric ID
            required: true
```

a request to this URI `http://localhost:3000/api/pages/examples` returns the example, when it should have thrown a validation error, as "examples" is not a valid number
