### ISSUE TITLE
Osprey silently fails if body does not have content-type in a PATCH

### ISSUE THREAD

**Issue by dmartinezg** [mulesoft/osprey-cli#63]
if you have a RAML like:

``` yaml
#%RAML 0.8
title: sample
/resource:
  patch:
```

Osprey silently fails
